Commenting out snappy compression in storage module
The test `storage::level::test::add_sstable` is getting the following
error message:

```
---- storage::level::test::add_sstable stdout ----
Error: invalid length 1701643008, expected binary length must be between 0 and 16777216
```

I still need to evaluate it further.